name: brilink
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  intl: ^0.20.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  firebase_crashlytics: ^5.0.1
  file_picker: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
