// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgdYydhqvO4zEuRLwTBfdzNsXgYKxvx8E',
    appId: '1:794708716058:web:53ea8dd317c85500e03fa3',
    messagingSenderId: '794708716058',
    projectId: 'brilink-5e825',
    authDomain: 'brilink-5e825.firebaseapp.com',
    storageBucket: 'brilink-5e825.firebasestorage.app',
    measurementId: 'G-QJYRFG4WNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg3Uk4wDX5N78BTDF208rmB6ElFjxrLTc',
    appId: '1:794708716058:android:47ad4cd6cf242acce03fa3',
    messagingSenderId: '794708716058',
    projectId: 'brilink-5e825',
    storageBucket: 'brilink-5e825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWlWDksransv4Lnf3aWRaio65yv_XNcJA',
    appId: '1:794708716058:ios:8544c6adbdc80a1fe03fa3',
    messagingSenderId: '794708716058',
    projectId: 'brilink-5e825',
    storageBucket: 'brilink-5e825.firebasestorage.app',
    iosBundleId: 'com.example.brilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWlWDksransv4Lnf3aWRaio65yv_XNcJA',
    appId: '1:794708716058:ios:8544c6adbdc80a1fe03fa3',
    messagingSenderId: '794708716058',
    projectId: 'brilink-5e825',
    storageBucket: 'brilink-5e825.firebasestorage.app',
    iosBundleId: 'com.example.brilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgdYydhqvO4zEuRLwTBfdzNsXgYKxvx8E',
    appId: '1:794708716058:web:97c6a3dfb2f23743e03fa3',
    messagingSenderId: '794708716058',
    projectId: 'brilink-5e825',
    authDomain: 'brilink-5e825.firebaseapp.com',
    storageBucket: 'brilink-5e825.firebasestorage.app',
    measurementId: 'G-N5VEPRCMG0',
  );
}
